name: pmdm_daniel_ramirez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/foto-ejercicio2.jpg
    - assets/images/foto1-ejercicio3.png
    - assets/images/foto2-ejercicio3.png
    - assets/images/foto3-ejercicio3.jpg
    - assets/images/foto1-ejercicio5.jpg
    - assets/images/foto2-ejercicio5.jpg
    - assets/images/foto3-ejercicio5.jpg
    - assets/images/foto4-ejercicio5.jpg
    - assets/images/foto5-ejercicio5.jpg
